# Generated by Django 4.0.6 on 2023-01-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=3)),
                ('num_documeneto', models.CharField(max_length=11)),
                ('nombres', models.CharField(max_length=175)),
                ('apellidos', models.CharField(max_length=175)),
                ('email', models.CharField(max_length=225)),
            ],
        ),
    ]
