# Generated by Django 4.0.6 on 2023-01-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_email_usuario_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='num_documento',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(max_length=3),
        ),
    ]
